[workspace]
members = ["apps/cli"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["Your Name <your.email@example.com>"]
homepage = "https://github.com/avadakedavra-wp/fazrepo"
repository = "https://github.com/avadakedavra-wp/fazrepo"
