# Release workflow for fazrepo
name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_extension: ""
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary_extension: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_extension: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_extension: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_extension: ".exe"
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            binary_extension: ".exe"

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Install cross-compilation tools
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Prepare binary
      run: |
        binary_name="fazrepo"
        if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
          export CC=aarch64-linux-gnu-gcc
        fi
        cp target/${{ matrix.target }}/release/${binary_name}${{ matrix.binary_extension }} ${binary_name}-${{ matrix.target }}${{ matrix.binary_extension }}
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: fazrepo-${{ matrix.target }}${{ matrix.binary_extension }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
